/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type DeviceType = "mobile" | "tablet" | "desktop" | "unknown";

export interface ParsedUserAgentInfo {
  /** Human-readable client, e.g. `"Chrome 151"` or `"Hosanna 1.0.4"`. */
  client: string | null;
  /** Human-readable OS, e.g. `"Android 14"` or `"macOS Sonoma"`. */
  os: string | null;
  /** Device model, e.g. `"Pixel 8"` or `"iPad"` (null for desktop/unknown). */
  device: string | null;
  deviceType: DeviceType;
  /** True when the UA was generated by a native (Flutter) app. */
  isApp: boolean;
}

const WINDOWS_VERSIONS: Record<string, string> = {
  "11.0": "Windows 11",
  "10.0": "Windows 10",
  "6.3": "Windows 8.1",
  "6.2": "Windows 8",
  "6.1": "Windows 7",
  "6.0": "Windows Vista",
  "5.1": "Windows XP",
  "5.0": "Windows 2000",
};

const MACOS_CODENAMES: Record<string, string> = {
  "10.15": "Catalina",
  "11": "Big Sur",
  "12": "Monterey",
  "13": "Ventura",
  "14": "Sonoma",
  "15": "Sequoia",
};

const OS_TOKEN =
  /^(Android|iOS|iPadOS|macOS|Mac OS X|Windows|Linux|Chrome OS)\b/;

/** `"151.0.0.0"` → `"151"`, `"17.4"` → `"17.4"`, `"128.0"` → `"128"`. */
function shortVersion(version: string): string {
  const [major, minor] = version.split(".");
  if (!minor || minor === "0") return major;
  return `${major}.${minor}`;
}

/**
 * Parses Flutter-app UAs like:
 * `Hosanna/1.0.4 (Android 14 (API 34); Pixel 8) Flutter/3.47.2`
 */
function parseFlutterUA(ua: string): ParsedUserAgentInfo | null {
  const match = ua.match(/^([^/]+)\/([\d.]+)\s*\((.+)\)\s*Flutter\/[\d.]+/);
  if (!match) return null;

  const [, appName, appVersion, platformInfo] = match;
  const segments = platformInfo
    .split(";")
    .map((segment) => segment.trim())
    .filter(Boolean);

  let os = "";
  let device = "";
  const osIndex = segments.findIndex((segment) => OS_TOKEN.test(segment));
  if (osIndex >= 0) {
    // Drop parenthesised details like "(API 34)".
    os = segments[osIndex].replace(/\s*\([^)]*\)/g, "").trim();
    device = segments.filter((_, index) => index !== osIndex).join(" ");
  } else if (segments.length > 0) {
    os = segments[0].replace(/\s*\([^)]*\)/g, "").trim();
    device = segments.slice(1).join(" ");
  }

  const osLower = os.toLowerCase();
  let deviceType: DeviceType;
  if (
    osLower.includes("android") ||
    osLower.includes("ios") ||
    osLower.includes("ipados")
  ) {
    deviceType =
      osLower.includes("ipad") || device.toLowerCase().includes("tablet")
        ? "tablet"
        : "mobile";
  } else if (
    osLower.includes("macos") ||
    osLower.includes("windows") ||
    osLower.includes("linux")
  ) {
    deviceType = "desktop";
  } else {
    deviceType = "unknown";
  }

  return {
    client: `${appName}${appVersion ? ` ${appVersion}` : ""}`,
    os: os || null,
    device: device || null,
    deviceType,
    isApp: true,
  };
}

/**
 * Parses classic browser UAs like:
 * `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
 * Chrome/151.0.0.0 Safari/537.36`
 */
function parseWebUA(ua: string): ParsedUserAgentInfo {
  /* Browser — check vendor products before the generic `Chrome/`. */
  const browserPatterns: Array<[RegExp, string]> = [
    [/Edg\/([\d.]+)/, "Edge"],
    [/OPR\/([\d.]+)/, "Opera"],
    [/SamsungBrowser\/([\d.]+)/, "Samsung Internet"],
    [/CriOS\/([\d.]+)/, "Chrome"],
    [/FxiOS\/([\d.]+)/, "Firefox"],
    [/Firefox\/([\d.]+)/, "Firefox"],
    [/Chrome\/([\d.]+)/, "Chrome"],
  ];
  let browser: string | null = null;
  let browserVersion: string | null = null;
  for (const [pattern, name] of browserPatterns) {
    const found = ua.match(pattern);
    if (found) {
      browser = name;
      browserVersion = found[1];
      break;
    }
  }
  if (!browser && /Safari\//.test(ua)) {
    const safariVersion = ua.match(/Version\/([\d.]+)/);
    browser = "Safari";
    browserVersion = safariVersion ? safariVersion[1] : null;
  }
  const client = browser
    ? browserVersion
      ? `${browser} ${shortVersion(browserVersion)}`
      : browser
    : null;

  /* Operating system. */
  let os: string | null = null;
  const windows = ua.match(/Windows NT ([\d.]+)/);
  if (windows) {
    os = WINDOWS_VERSIONS[windows[1]] ?? `Windows ${windows[1]}`;
  } else if (ua.includes("CrOS")) {
    os = "Chrome OS";
  } else {
    const ios = ua.match(/OS ([\d_]+) like Mac OS X/);
    const mac = ua.match(/Mac OS X ([\d_]+)/);
    if (ios) {
      os = `iOS ${ios[1].replace(/_/g, ".")}`;
    } else if (mac) {
      const version = mac[1].replace(/_/g, ".");
      const majorMinor = version.split(".").slice(0, 2).join(".");
      os = MACOS_CODENAMES[majorMinor]
        ? `macOS ${MACOS_CODENAMES[majorMinor]}`
        : `macOS ${version}`;
    } else if (/Android/.test(ua)) {
      const android = ua.match(/Android ([\d.]+)/);
      os = android ? `Android ${android[1]}` : "Android";
    } else if (/Linux/.test(ua)) {
      os = "Linux";
    }
  }

  /* Device type and model. */
  let device: string | null = null;
  let deviceType: DeviceType = "desktop";
  if (/iPad/.test(ua)) {
    deviceType = "tablet";
    device = "iPad";
  } else if (/iPhone/.test(ua)) {
    deviceType = "mobile";
    device = "iPhone";
  } else if (/iPod/.test(ua)) {
    deviceType = "mobile";
    device = "iPod";
  } else if (/Android/.test(ua)) {
    const androidDevice = ua.match(/Android [\d.]+; ([^;)]+)/);
    const model = androidDevice
      ? androidDevice[1].replace(/ Build\/.*$/, "").trim()
      : "";
    if (model && model !== "Mobile" && model !== "Tablet") device = model;
    deviceType = /Tablet/.test(ua)
      ? "tablet"
      : /Mobile/.test(ua)
        ? "mobile"
        : device
          ? "tablet"
          : "desktop";
  } else if (/Mobile/.test(ua)) {
    deviceType = "mobile";
  }

  return { client, os, device, deviceType, isApp: false };
}

/** Parses a raw user agent into a friendly, human-readable description. */
export function parseUserAgent(userAgent?: string | null): ParsedUserAgentInfo {
  if (!userAgent) {
    return {
      client: null,
      os: null,
      device: null,
      deviceType: "unknown",
      isApp: false,
    };
  }
  return parseFlutterUA(userAgent) ?? parseWebUA(userAgent);
}
